### ISSUE TITLE
Uncaught invalid cipher format version

### ISSUE THREAD

**Issue by NeoMod** [klingenm/passwordbox-export#3]
After reading the response given in the previous erroneous “bug report” I followed again all the procedure, double-checking all steps.

Ignoring the “undefined” output error I tried to run the export command “MK.exportFor1PasswordToClipboard()” but the following error presented:

“Uncaught invalid cipher format version”.

Same error presents while using “MK.exportCsvToClipboard()” command.
In both cases nothing is copied to clipboard.

Below I have attached a screenshot of the error, which I am not sure at this point if should be considered a bug or not.

![error](https://cloud.githubusercontent.com/assets/13747261/10143368/32052034-6618-11e5-9bb2-47068b95a34e.jpg)

Testing platform was as follows:
S.O. : Win 10 x64
Chrome 47.0.2521.0 canary (64-bit)
P.B. Version 1.38.11.4204

**Comment by enoversum** [comment]
+1 here, would be great to get a little hint into the right direction. Read the closed thread about the 'undefined' error, but it unfortunately didn’t help, as your code has already been updated to work well as far as I can see.

**Comment by Sotilrac** [comment]
+1Any tips are welcome

**Comment by nickast** [comment]
+1 Here

**Comment by NeoMod** [comment]
I'm sorry not to bear any good news. 
I've managed to obtain the old PB Extension for Chrome, which should supposedly work with this script, but results where inconclusive as well.
No error thrown out in Console but the MK.export function did not provide any data.

**Comment by AbuMaia** [comment]
How did you obtain an old PB extension? I was just in chat with them, and was assured I was not allowed to download an older extension.

**Comment by klingenm** [comment]
Hi!

Sorry not to answer before now. Regrettably I don't have any time to put on
supporting this "hack".

@NeoMod, even if you use an old version, chances are that the database of
passwords is migrated when the extension is updated. Thus the use of an
older version may be discouraged for the reason that doing so actually
could corrupt your personal password database.

@NeoMod, also the error message in your message points to the fact that they have changed something. Not sure what. The procedure you did now is the correct now and that is the way it should work. I'll update the readme so that no more waists time on trying.

**Comment by vhalik** [comment]
Refer to comment https://github.com/klingenm/passwordbox-export/issues/1#issuecomment-131197030
You can then use any of the functions like exportCsvToClipboard() or exportCsv() after following the instructions and you will get the output. I can verify it. I was able to extract all my passwords lastnight. I am running PasswordBox version 1.38.11.4209

A side note: Ignore "undefined" that is returned after running the script. You can still use the functions to retrieve your data.

**Comment by NeoMod** [comment]
Thank you vhalik, Please beg my pardon but could you please post the following details to help us out?  - What version of Chrome did you use? - What OS are you on? - Can you please describe step-by-step procedure?  Again please beg me but I tried dozens of times without any luck, an not only me but all of my colleagues using PB weren't able to made it work: since its crucial for us to escape from PB trap, your help would be much appreciated!   

---Sent from Boxer | http://getboxer.com

On 11 dicembre 2015 19:50:01 CET, Timothy Soliday notifications@github.com wrote:Refer to comment #1 (comment) You can then use any of the functions like exportCsvToClipboard() or exportCsv() after following the instructions and you will get the output. I can verify it. I was able to extract all my passwords lastnight. I am running PasswordBox version 1.38.11.4209  A side note: Ignore "undefined" that is returned after running the script. You can still use the functions to retrieve your data.  —Reply to this email directly or view it on GitHub.

**Comment by nickast** [comment]
Hi vhalik, I can verify that the process does not work. :(

**Comment by vhalik** [comment]
You bet!

OS = OS X El Capitan v10.11.2
Google Chrome = Version 47.0.2526.80 (64-bit)
PasswordBox = 1.38.11.4209

Make sure you are logged in to your PasswordBox extension before you do anything else. 
**1.** Go to extensions which is under preferences for me. 
**2.** Scroll down to the PasswordBox extension and click on "background page". Looks like this:
![screen shot 2015-12-11 at 5 23 46 pm](https://cloud.githubusercontent.com/assets/989173/11758746/22518968-a02c-11e5-9e96-92a32703eec7.png)
![screen shot 2015-12-11 at 5 24 00 pm](https://cloud.githubusercontent.com/assets/989173/11758747/257c224c-a02c-11e5-8e70-2e4148c584bf.png)
I do recommend getting familiar with [Chrome Developer Tools](https://developer.chrome.com/devtools)
**3.** Just like what lfbarbieri says in his post https://github.com/klingenm/passwordbox-export/issues/1#issuecomment-131197030 Only copy lines 6 through 131 from export.js.
**4.** Paste that into into the window that popped up when you clicked on "background page". You will paste it under the console tab. It looks like this
![screen shot 2015-12-11 at 5 05 17 pm](https://cloud.githubusercontent.com/assets/989173/11758547/64bbeaf8-a029-11e5-89d8-341f9e0230a3.png)
You want to paste it where the blue greater than sign is located. I know, it is only one line, but trust me it will take everything you pasted.
**5.** Once you paste it and hit Enter you will get something like this
![screen shot 2015-12-11 at 5 07 38 pm](https://cloud.githubusercontent.com/assets/989173/11758580/c633b108-a029-11e5-89fe-b18a7118feb0.png) 
It will say undefined. That is ok.
**6.** Type one of these functions and hit enter

```
exportCsv()
exportFor1Password()
exportCsvToClipboard()
exportFor1PasswordToClipboard()
```

**7.** For this example I chose `exportCsv()`
![screen shot 2015-12-11 at 5 13 52 pm](https://cloud.githubusercontent.com/assets/989173/11758623/9623040e-a02a-11e5-9462-1f6216dd3ca0.png)

**8.** Here is my output
![screen shot 2015-12-11 at 5 19 51 pm](https://cloud.githubusercontent.com/assets/989173/11758687/71e247ca-a02b-11e5-9f09-b109bac2ebd7.png)

**Comment by vhalik** [comment]
I am going to try this on Windows 10 tonight and let everyone know

**Comment by NeoMod** [comment]
Thank you for your super-kind answer Timothy!

I've run the same procedure over _Win10_ with _Chrome *_48.0.2564.41*
beta-m *(64-bit) *but apparently PB works differently in this OS.

If I use the very _same command *you use for_ Point 5_, *6_, and _7_ my _output
*comes *"blank"_ :
https://cloud.githubusercontent.com/assets/13747261/11878302/3802572e-a4f5-11e5-9039-efc1622fa4c3.jpg

​_I've also tried to specify some config options_ but then the output
results with following errors / warning :
https://cloud.githubusercontent.com/assets/13747261/11878306/40a4047c-a4f5-11e5-83db-19f53479ab1e.jpg

​The only thing I can think of, except for beeing on a different OS, is
about PB Versions: you succeded using version 1.38.11.4209 while I failed
with 1.38.11.4210. I'll try to "downgrade" the extension and see if it
works that way.

In the meantime, thank you very much for your help and your courtesy! If
you ever plan a trip to Italy, there is a lot of Pizza waiting in your
name! :-D

**Comment by NeoMod** [comment]
Neither downgrading the extension has been useful in solving the issue.
Here it is my output:
https://cloud.githubusercontent.com/assets/13747261/11878287/13844506-a4f5-11e5-8ae5-d70c798a993c.jpg

**Comment by deviant77** [comment]
I must say a big thank you to @klingenm, who taking the time to share this. It's proved invaluable for exporting several hundred entries over a couple of accounts.

It does work. I've used it several times, and most recently today.

Windows 10 and Ubuntu 15.10 (64-bit).
Chrome version 47.0.2526.106 (64-bit).
PasswordBox extension version 1.38.11.4209.
Using the latest version of export.js (with all the commits up to Dec 2, 2015).

vhalik has documented the method I used with the following differences:

Steps 3 and 4: I copied and pasted the _whole_ script in to the console tab.

Step 5: I can confirm that it's normal to see the "undefined" message.

Step 6: The command I used is `MK.exportCsvToClipboard()` to export all entries to the clipboard.

Step 8: My output was:
    You are running PasswordBox 1.38.11.4209. This has only been tested on 1.38.9.4120
    Extracted 106 records from your database.
    Exported result to clipboard.
    undefined

**Comment by enoversum** [comment]
Well, I am really curious as why this is working for you, while I still fail. The steps are fairly easy to reproduce, especially when you use Developer tools all day like me. Pasting the code or even from line 6 still give me no export to my clipboard, but the cipher error. The PW box version is the same as mine, only I use the beta version of Chrome (48 x64).

**Comment by deviant77** [comment]
Have you claimed your promotional TrueKey account (and therefore automatically migrated your passwords over)?
I haven't, and I wondered if this could be something to do with it.

**Comment by NeoMod** [comment]
Once claimed the TrueKey account it is impossible to access PB again, so that's not the case.

I have tried on Windows 10 the very same procedure but with negative result: no data was exported, as documented before, neither to CSV nor to Clipboard.

I'm wondering if this could result from the number of passwords stored inside your profile: my PB cotains over 800 passwords, while your output was successful with just a little more than 100.

@enoversum did you have more than 100 passwords inside your PB ?

**Comment by enoversum** [comment]
@NeoMod I have ~350 passwords, and no, since I do want to break free from PasswordBox/Intel, I did not transform my account to TrueKey.

**Comment by deviant77** [comment]
I successfully exported ~280 from another account.

**Comment by NeoMod** [comment]
Well apparently some of us suffers from "bad karma" :8ball: since the procedure was a fail. I'm happy that at least some of you has been able to escape from PB.
