### ISSUE TITLE
Does not appear to work with version 1.38.11.4209

### ISSUE THREAD

**Issue by BrianHeston** [klingenm/passwordbox-export#4]
When I try to run the snippet, it just comes back with "undefined".

Any chance we can get this updated to work with the latest version since they're pulling the rug out from under us?

Thanks!

**Comment by AbuMaia** [comment]
I, too, am getting "undefined" in the console of the Developer Tools window. I need this to work so I can dump PasswordBox.

edit: I looked at the "invalid" issue where people were also reporting the "undefined". I tried some of the tips there, but I have not gotten it to work. I'm getting this error now:

You are running PasswordBox 1.38.11.4209. This has only been tested on 1.38.9.4120
background-app.js:2 Uncaught invalid cipher format version

It appears that FA.Background.decryptWithAES is no longer working properly. I have no idea with what I should replace the AES to proceed from here.

**Comment by klingenm** [comment]
Sad to say I don't have any time to reverse engineer this again...  any pull requests are welcome.

**Comment by vhalik** [comment]
Refer to comment https://github.com/klingenm/passwordbox-export/issues/1#issuecomment-131197030
You can then use any of the functions like exportCsvToClipboard() or exportCsv() after following the instructions and you will get the output. I can verify it. I was able to extract all my passwords lastnight. I am running PasswordBox version 1.38.11.4209

A side note: Ignore "undefined" that is returned after running the script. You can still use the functions to retrieve your data.
